@startuml

!include estilos.puml

title Caso de uso: Un socio con plan fan de las clases quiere reservar la sala de musculación pero ya llegó a su límite

actor test as "Test02"

participant socio as "socio:Socio"
participant plan as "plan:FanDeLasClases"
participant gimnasio as ":Gimnasio"
participant agenda as ":AgendaGimnasio"
participant excepcion as ":LimiteDeReservasAlcanzadoExcepcion"

test -> agenda ** : AgendaGimnasio()
test -> gimnasio ** : Gimnasio(agenda)

test -> plan ** : PlanFanDeLasClases()
test -> socio ** : Socio(plan)
test -> gimnasio : agregarSocio(socio)

test -> socio : reservarSalaMusculacion()
activate socio
socio -> plan : reservarSalaMusculacion(socio)
activate plan
plan -> agenda : cuantasVecesReservadasASalaMusculacion(socio)
activate agenda
agenda --> plan : 0
deactivate agenda

plan -> plan : verificarMaximoDeReservasASalaMusculacion(0)
activate plan
deactivate plan
plan -> agenda : reservarSalaMusculacion(socio)
deactivate plan
deactivate socio

test -> socio : reservarSalaMusculacion()
activate socio
socio -> plan : reservarSalaMusculacion(socio)
activate plan
plan -> agenda : cuantasVecesReservadasASalaMusculacion(socio)
activate agenda
agenda --> plan : 1
deactivate agenda

plan -> plan : verificarMaximoDeReservasASalaMusculacion(1)
activate plan
deactivate plan
plan -> agenda : reservarSalaMusculacion(socio)
deactivate plan
deactivate socio

test -> socio : reservarSalaMusculacion()
activate socio
socio -> plan : reservarSalaMusculacion(socio)
activate plan
plan -> agenda : cuantasVecesReservadasASalaMusculacion(socio)
activate agenda
agenda --> plan : 2
deactivate agenda

plan -> plan : verificarMaximoDeReservasASalaMusculacion(2)
activate plan
plan -> excepcion ** : LimiteDeReservasAlcanzadoExcepcion()
deactivate plan
deactivate plan

deactivate socio

@enduml